name = "orange-hill-0081"
main = "src/index.ts"
compatibility_date = "2023-09-04"
compatibility_flags = [ "nodejs_compat" ]

[vars]
BASE_PATH="/blog"
DELIVERY_API_KEY=""
WEBHOOK_SECRET=""

[[kv_namespaces]]
binding = "BLOG_CACHE"
preview_id = "f968651821d24ffea717133abf4d5dc9"
id = "6fff130feee94372aa3b8a1892f25e65"
